spring:
  application:
    name: simpsons-corp
  data:
    mongodb:
      database: simpsonsdb

server:
  port: 8083
  servlet:
    context-path: /${spring.application.name}/api

logging:
  file: application.log